name: Pnpm License Collector
author: DaniFoldi
description: Collect licenses of dependencies, fail if some don't match the whitelist
branding:
  color: yellow
  icon: check-square
inputs:
  directory:
    description: 'Package directory'
    required: false
    default: '.'
  allowed:
    description: 'Whitelist of allowed licenses'
    required: true
    default: [MIT]
  ignored:
    description: 'List of packages to ignore'
    required: false
    default: []
runs:
  using: 'node20'
  main: 'index.js'
